routes/web.php
<?php
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('modify-migration', function(){
  $result = DB::table('migrations')->where('id',13)->delete();
  $result = DB::table('migrations')->get();
  print($result);
});
Route::get('services',function(){
  return view('services');
});
Route::get('language/{lang}','HomeController@changeLanguage');
Route::post('add_skills','UserController@addSkills');
Route::get('publishBlog/{slug}','HomeController@publishBlog');
Route::get('publishWork/{slug}','HomeController@publishWork');
Route::get('unpublishWork/{slug}','HomeController@unpublishWork');
Route::get('unpublishBlog/{slug}','HomeController@unpublishBlog');
Route::get('search','BlogController@searchByKeyword');
Route::get('vote','BlogController@voteArticle');
Route::post('update-password','UserController@changePassword');
Route::get('update-password',function(){
  return view('auth.passwords.update');
})->middleware('auth');

/*Route::get('portofolio',function(){
  return view('portofolio');
});
Route::get('blog',function(){
   return view('blog');
});*/
Route::get('new-web-case', function(){
  return view('newwebdesign');
});
Route::get('new-ui-case', function(){
  return view('newuidesign');
});

Route::post('newuicase','newcaseController@storeui');
Route::get('new-seo-case', function(){
  return view('newposterdesign');
});
Route::get('new-seo-case/{id}','newcaseController@storeSeoClient');
Route::get('new-web-case/{id}','newcaseController@storeWebClient');
Route::get('new-ui-case/{id}','newcaseController@storeMobileClient');
Route::post('newpostercase','newcaseController@storeposter');
Route::post('newwebcase','newcaseController@storeweb');
Route::get('/', function () {
    return redirect('home');
});
Route::get('newcase',function(){
	return view('newcase');
});
Route::get('remove-skill/{skill}','UserController@removeSkill');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('newcase','newcaseController@store');
Route::resource('blog','BlogController');
Route::post('message','HomeController@sendMessage');
Route::resource('portofolio','PortofolioController');
Route::get('add-user',function(){
  return redirect()->route('users.create');
})->middleware('auth');
Route::resource('users','UserController');
Route::get('/oauth/github', 'AuthController@redirectToProvider');
Route::get('/oauth/github/callback', 'AuthController@handleProviderCallback');
Route::post('change_pic','AuthController@changePic');
Route::get('/savecookie','newcaseController@savecookie');

resources/views/shared/best_authors.blade.php
<div class="row">
  <!-- best authors -->
  <div class="col-md-12" style="text-align:center">
    <h5>{{trans('app.our_best_authors_of_the_month')}}</h5>
    @foreach($users as $user)
      <div class=" col-sm-3 card" style="text-align:center">
        <div class="fakeimg">
          <a href="{{url('users/'.$user->username)}}">
            <img src="{{asset('img/users/'.$user->image)}}">
            <h5>{{$user->username}}</h5>
          </a>
          <p>
              {{trans('app.joined')}}
            <i class="fa fa-clock-o">                   
            </i>
                {{(new Carbon\Carbon($user->created_at))->diffForHumans()}}</p>
        </div>    
      </div>
    @endforeach
  </div> 
</div>

resources/views/shared/blog_post.blade.php
<div class="row">
  <div class="col-md-2" style="position:auto">
    @foreach(trans('app.post_categories') as $key => $value)
      <a href="{{url('category/'.str_slug($value,'-'))}}" class="badge badge-dark badge-pill">
        {{$value}}
      </a>
        <hr>
    @endforeach
  </div>
  <div class="col-md-10">
    @foreach($blogs as $blog)
          <div class="col-md-{{(count($blogs)==1)?12:8}} col-sm-{{(count($blogs)==1)?12:6}} portfolio-item" id="desc">
            <a class="portfolio-link" href="{{route('blog.show',$blog->slug)}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-eye fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              <a href="{{route('blog.show',$blog->slug)}}">
                <h4>{{(strlen($blog->title)>20)?mb_substr(strip_tags($blog->title),0,20).'..':$blog->title}}</h4>
                <p class="text-muted">{{(strlen($blog->subtitle))?mb_substr(strip_tags($blog->subtitle),0,60).'..':$blog->subtitle}}</p>
              </a>
              <p>
                <?php $tags=explode(",",$blog->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}

            @endforeach
              </p>
              <p>
               @if(Auth::check() && Auth::user()->id==$blog->user_id)
                 <a href="{{route('blog.edit',$blog->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                @endif
                <i class="fa fa-clock-o">
                  
               </i>
              {{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</p>
            </div>

          </div>
@endforeach
  </div>

@if(isset($asc_blogs))
@foreach($asc_blogs as $blog)
          <div style="display:none;" class="col-md-{{(count($asc_blogs)==1)?12:4}} col-sm-{{(count($asc_blogs)==1)?12:6}} portfolio-item" id="asc">
            <a class="portfolio-link" href="{{route('blog.show',$blog->slug)}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-eye fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              <a href="{{route('blog.show',$blog->slug)}}">
                <h4>{{mb_substr(strip_tags($blog->title),0,20)}}...</h4>
                <p class="text-muted">{{mb_substr(strip_tags($blog->subtitle),0,60)}}...</p>
              </a>
              <p>
                <?php $tags=explode(",",$blog->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}

            @endforeach
              </p>
              <p>
                @if(Auth::check() && Auth::user()->id==$blog->user_id)
                 <a href="{{route('blog.edit',$blog->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                @endif
                <i class="fa fa-clock-o" ></i>
                
                  
                </i>
                {{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</p>
            </div>

          </div>
@endforeach
@endif
@if(Auth::check()&& isset($user) && Auth::user()->id==$user->id && isset($unpublishedBlogs))

@foreach($unpublishedBlogs as $blog)
          <div  class="col-md-{{(count($unpublishedBlogs)==1)?12:4}} col-sm-{{(count($unpublishedBlogs)==1)?12:6}} portfolio-item" id="asc">
            <a class="portfolio-link" href="{{route('blog.show',$blog->slug)}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-eye fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              @if(count($blogs)<=2)
              <h4>{{mb_substr(strip_tags($blog->title),0,10)}}...</h4>
              @else
              <h4>{{mb_substr(strip_tags($blog->title),0,20)}}...</h4>
              @endif
              <p class="text-muted">{{mb_substr(strip_tags($blog->subtitle),0,60)}}...</p>
              <p>

                <?php $tags=explode(",",$blog->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}

            @endforeach
              </p>

              <p>
                <a href="{{route('blog.edit',$blog->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                <i class="fa fa-lock" style="color:red;"></i>
                <i class="fa fa-clock-o">
                  
                </i>
                {{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</p>
            </div>

          </div>
@endforeach
@endif
@if(count($blogs)>6)
<div style="text-align:center;">
    <a href="{{url('portofolio')}}" class="btn btn-primary">{{trans('app.see_more')}}</a>
</div>
@endif
</div>

resources/views/shared/filter_by_category.blade.php
<script>
    document.getElementById('filter').addEventListener('click', function (event) {
        if (event.target.tagName === 'A') {
            event.preventDefault(); // Prevent the default link behavior
            if (event.target.classList.contains('active')) {
               event.target.classList.remove('active');
               location.reload()
            }else{
              var clickedValue = event.target.innerText.trim();
              var categoryItems = document.querySelectorAll('.category');
            

            // Iterate over each list item in .category
              categoryItems.forEach(function (item) {
                  var categoryValue = item.innerText.trim();

                  // Check if the clicked value is different from the category value
                  if (clickedValue !== categoryValue) {
                      // Hide the list item
                      console.log(item.parentNode.parentNode.parentNode)
                      item.parentNode.parentNode.parentNode.style.display = 'none';
                  } else {
                      // If the clicked value matches the category value, show the list item
                      item.parentNode.parentNode.parentNode.style.display = 'block';
                  }
              });

               // Remove the 'active' class from all links and add it to the clicked link
              var links = document.querySelectorAll('#filter a');
              links.forEach(function (link) {
                  link.classList.remove('active');
              });
              event.target.classList.add('active');
              }
              
        }
    });
</script>

resources/views/shared/grid.blade.php
<div class="row">

@foreach($works as $work)
         <div class="col-md-{{(count($works)==1)?12:4}} col-sm-{{(count($works)==1)?12:6}} portfolio-item" id="desc">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal{{$work->id}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/portfolio/'.$work->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              @if(count($works)<=2)
              <h4>{{(strlen($work->title)>10)?mb_substr(strip_tags($work->title),0,10).'..':$work->title}}
              </h4>
              @else
              <h4>{{(strlen($work->title)>20)?mb_substr(strip_tags($work->title),0,20).'..':$work->title}}
              </h4>
              @endif
              <p class="text-muted">{{config('category.category_'.$work->cat_id)}}</p>
              <p>
                <?php $tags=explode(",",$work->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}
            @endforeach
              </p>
              <p>
                @if(Auth::check() && Auth::user()->id==$work->user_id)
                 <a href="{{route('portofolio.edit',$work->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                @endif
                <i class="fa fa-clock-o">
                  
                </i>
                {{(new Carbon\Carbon($work->created_at))->diffForHumans()}}</p>
            </div>
          </div>
@endforeach

@if(Auth::check() && isset($user) && Auth::user()->id==$user->id)
@foreach($unpublishedWorks as $work)
         <div class="col-md-{{(count($unpublishedWorks)==1)?12:4}} col-sm-{{(count($unpublishedWorks)==1)?12:6}} portfolio-item" id="desc">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal{{$work->id}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/portfolio/'.$work->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>{{(strlen($work->title)>20)?mb_substr(strip_tags($work->title),0,20).'..':$work->title}}
              </h4>
              <p class="text-muted">{{config('category.category_'.$work->cat_id)}}</p>
              <p>
                <?php $tags=explode(",",$work->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}
            @endforeach
              </p>
              <p>
                 <a href="{{route('portofolio.edit',$work->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                <i class="fa fa-lock" style="color:red;"></i>
                <i class="fa fa-clock-o">
                  
                </i>
                {{(new Carbon\Carbon($work->created_at))->diffForHumans()}}</p>
            </div>
          </div>
@endforeach

@endif


@if(isset($asc_works))
@foreach($asc_works as $work)
         <div class="col-md-{{(count($asc_works)==1)?12:4}} col-sm-{{(count($asc_works)==1)?12:6}} portfolio-item" id="asc" style="display:none;">
            <a class="portfolio-link" data-toggle="modal" href="#portfolioModal{{$work->id}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-plus fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/portfolio/'.$work->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              <h4>{{mb_substr(strip_tags($work->title),0,20)}}...
              </h4>
              <p class="text-muted">

                
                {{config('category.category_'.$work->cat_id)}}</p>
              <p>
                <?php $tags=explode(",",$work->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}
            @endforeach
              </p>
              <p>
                @if(Auth::check() && Auth::user()->id==$work->user_id)
                 <a href="{{route('portofolio.edit',$work->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                @endif
                <i class="fa fa-clock-o">
                  
                </i>
                {{(new Carbon\Carbon($work->created_at))->diffForHumans()}}</p>
            </div>
          </div>
@endforeach

@endif
@if(count($works)>6)
<div style="text-align:center;">
    <a href="{{url('portofolio')}}" class="btn btn-primary">{{trans('app.see_more')}}</a>
</div>
@endif
</div>

resources/views/shared/home_blogs.blade.php
<div class="row-with-filter">
  <div class="row fixed-filter-row" style="text-align:center;" >
    <div class="col-md-1">
      
    </div>
    <div class="col-md-10" id="filter">
      @foreach(trans('app.post_categories') as $key => $value)
        <a href="" class="badge badge-dark badge-pill" style="display: inline-block;">
          {{$value}}
        </a>
      @endforeach
    </div>
  
  </div>
</div>
  

<div class="row content-margin">

  <div class="col-md-8 col-xs-offset-2">
    @foreach($blogs as $blog)
          <div class="col-md-{{(count($blogs)==1)?12:12}} col-sm-{{(count($blogs)==1)?12:12}} portfolio-item" id="desc">
            <a class="portfolio-link" href="{{route('blog.show',$blog->slug)}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-eye fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              <a href="{{route('blog.show',$blog->slug)}}">
                <h4>{{(strlen($blog->title)>20)?mb_substr(strip_tags($blog->title),0,20).'..':$blog->title}}</h4>
                <p class="text-muted">{{(strlen($blog->subtitle))?mb_substr(strip_tags($blog->subtitle),0,60).'..':$blog->subtitle}}</p>
              </a>
              <p>
                <?php $tags=explode(",",$blog->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}

            @endforeach
              </p>
              <p>
               @if(Auth::check() && Auth::user()->id==$blog->user_id)
                 <a href="{{route('blog.edit',$blog->slug)}}">
                  <i class="fa fa-pencil"></i>
                </a>
                @endif
               
               <p>
                  <small class="category"> {{trans('app.post_categories')[$blog->cat_id]}}</small>
               </p>
               <p>
                 <i>
                   {{trans('app.revelancy')}} : {{$blog->votes}}
                 </i>
               </p>
                <i class="fa fa-clock-o">
                  
               </i>
              {{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</p>
            </div>

          </div>
    @endforeach
    
    
  </div>
  <!-- our recommendations -->
  <div class="col-md-4" style="text-align:center">
    <h5>{{trans('app.our_recommendation')}}</h5>
    @foreach($recommendations as $post)
      <div class="card" style="text-align:center">
        <div class="fakeimg">
          <a href="{{url('blog/'.$post->slug)}}">
          
             <h6>{{(strlen($post->title)>20)?mb_substr(strip_tags($post->title),0,25).'..':$post->title}}</h6>
              <p class="text-muted">{{(strlen($post->subtitle))?mb_substr(strip_tags($post->subtitle),0,60).'..':$post->subtitle}}</p>
          </a>
          <p>
              {{trans('app.posted')}}
            <i class="fa fa-clock-o">                   
            </i>

                {{(new Carbon\Carbon($post->created_at))->diffForHumans()}}</p>
        </div>    
      </div><br>
    @endforeach
  </div>
</div>

@include('shared.filter_by_category')

resources/views/shared/preview_work.blade.php
<div class="portfolio-modal modal fade" id="previewWork" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="close-modal" data-dismiss="modal">
            <div class="lr">
              <div class="rl"></div>
            </div>
          </div>
          <div class="container">
            <div class="row">
              <div class="col-lg-8 mx-auto">
                <div class="modal-body">
                  <!-- Project Details Go Here -->
                  <h2 class="text-uppercase">{{$work->title}}</h2>
                  <p class="item-intro text-muted">{{$work->subtitle}} </p>
                  <img style="width:100%; height:700px;" class="img-responsive img-fluid d-block" src="{{asset('img/portfolio/'.$work->image)}}" alt="">
                  <p>{!!$work->content!!}</p>
                  <ul class="list-inline">
                    <li>{{trans('app.date')}}: {{$work->created_at}}
                    </li>
                    <li>{{trans('app.client')}}: {{$work->client}}
                    </li>
                    <li>{{trans('app.Category')}}: {{config('category.category_'.$work->cat_id)}}
                    </li>

                  </ul>
                  <p>
                <?php $tags=explode(",",$work->tags); ?>
                     @foreach($tags as $tag)
                      {{'#'.$tag}}
                     @endforeach
                  </p>
                  <button class="btn btn-primary" data-dismiss="modal" type="button">
                    <i class="fa fa-times"></i>
                    {{trans('app.close')}}</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

resources/views/shared/pricing.blade.php
<section id="about" style="margin-left:10%;">
      <div class="container">
        <div class="row">
          <div class=" col-sm-12 col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">{{trans('app.pricing')}}</h2>
            
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4">
            <div class="card" style="width: 18rem;">
              <div class="card-header">
                {{trans('app.mobile_dev')}}
              </div>
             <ul class="list-group list-group-flush">
                <li class="list-group-item">50$/hr</li>
                <li class="list-group-item">{{trans('app.delivery_in')}} : 3 {{trans('app.weeks')}}</li>
                <li class="list-group-item">
                <a id="hire_mobile" href="{{url('new-ui-case')}}" class="btn btn-danger" role="button">{{trans('app.submit_project')}}</a>
                </li>
             </ul>
           </div>
            
          </div>
          <div class="col-lg-4">
            <div class="card" style="width: 18rem;">
              <div class="card-header">
                {{trans('app.web_design')}}
              </div>
             <ul class="list-group list-group-flush">
                <li class="list-group-item">120$/hr</li>
                <li class="list-group-item">{{trans('app.delivery_in')}} : 3 {{trans('app.weeks')}}</li>
                <li class="list-group-item">
                <a id="hire_web" href="{{url('new-web-case')}}" class="btn btn-danger" role="button">{{trans('app.submit_project')}}</a>
                </li>
             </ul>
           </div>
            
          </div>
          <div class="col-lg-4">
            <div class="card" style="width: 18rem;">
              <div class="card-header">
                {{trans('app.seo')}}
              </div>
             <ul class="list-group list-group-flush">
                <li class="list-group-item">20$/hr</li>
                <li class="list-group-item">{{trans('app.delivery_in')}} : 3 {{trans('app.weeks')}}</li>
                <li class="list-group-item">
                <a id="hire_seo" href="{{url('new-seo-case')}}" class="btn btn-danger" role="button">{{trans('app.submit_project')}}</a>
                </li>
             </ul>
           </div>
            
          </div>
          
      </div>
    </section>

resources/views/shared/user_blogs.blade.php
<div class="row">
  <div class="col-md-4">
    
  </div>
  <div class="col-md-6" style="position:auto" id="filter">
    @foreach(trans('app.post_categories') as $key => $value)
      <a href="" class="badge badge-dark badge-pill" style="display:inline-block;">
        {{$value}}
      </a>
    @endforeach
  </div>
  <div class="col-md-2">
    
  </div>
</div>
<hr>
<div class="row">
  
    @foreach($blogs as $blog)
          <div class="col-md-{{(count($blogs)==1)?12:4}} col-sm-{{(count($blogs)==1)?12:4}} portfolio-item" id="desc">
            <a class="portfolio-link" href="{{route('blog.show',$blog->slug)}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-eye fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              <a href="{{route('blog.show',$blog->slug)}}">
                <h4>{{(strlen($blog->title)>20)?mb_substr(strip_tags($blog->title),0,20).'..':$blog->title}}</h4>
                <p class="text-muted">{{(strlen($blog->subtitle))?mb_substr(strip_tags($blog->subtitle),0,60).'..':$blog->subtitle}}</p>
              </a>
              <p>
                <?php $tags=explode(",",$blog->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}

            @endforeach
              </p>
              <p>
               @if(Auth::check() && Auth::user()->id==$blog->user_id)
                 <a href="{{route('blog.edit',$blog->slug)}}" title="modifier résumé">
                  <i class="fa fa-pencil"></i>
                </a>
                @endif
                <p>
                  <small class="category"> {{trans('app.post_categories')[$blog->cat_id]}}</small>
               </p>
                <i class="fa fa-clock-o">
                  
               </i>
              {{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</p>
            </div>

          </div>
  @endforeach
</div>
  


@if(Auth::check()&& isset($user) && Auth::user()->id==$user->id && isset($unpublishedBlogs))

@foreach($unpublishedBlogs as $blog)
          <div  class="col-md-{{(count($unpublishedBlogs)==1)?12:4}} col-sm-{{(count($unpublishedBlogs)==1)?12:6}} portfolio-item" id="asc">
            <a class="portfolio-link" href="{{route('blog.show',$blog->slug)}}">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fa fa-eye fa-3x"></i>
                </div>
              </div>
              <img class="img-fluid" src="{{asset('img/blog/'.$blog->image)}}" alt="">
            </a>
            <div class="portfolio-caption">
              @if(count($blogs)<=2)
              <h4>{{mb_substr(strip_tags($blog->title),0,10)}}...</h4>
              @else
              <h4>{{mb_substr(strip_tags($blog->title),0,20)}}...</h4>
              @endif
              <p class="text-muted">{{mb_substr(strip_tags($blog->subtitle),0,60)}}...</p>
              <p>

                <?php $tags=explode(",",$blog->tags); ?>
            @foreach($tags as $tag)
            {{'#'.$tag}}

            @endforeach
              </p>

              <p>
                <a href="{{route('blog.edit',$blog->slug)}}" title="modifier résumé">
                  <i class="fa fa-pencil"></i>
                </a>
                <i class="fa fa-lock" style="color:red;" title="ce résumé est privé"></i>
                <i class="fa fa-clock-o">
                  
                </i>
                {{(new Carbon\Carbon($blog->created_at))->diffForHumans()}}</p>
            </div>

          </div>
@endforeach
@endif
@include('shared.filter_by_category')

resources/views/shared/users.blade.php
@if(isset($asc_users))
  
@include('shared.sort')
@endif
<div id="list">
@foreach($users as $user)
<div class="container" id="desc">
    <div class="card flex-row flex-wrap">
        <div class="card-header border-0">
            <img class="profileimage" src="{{asset('img/users/'.$user->image)}}" alt="">
        </div>
        <div class="card-block px-2">
            
                <h4 class="card-title">
                <span>
                    {{$user->name}} 
                     
                </span>
               
               </h4>
                @if(Auth::check() && Auth::user()->id != $user->id && Auth::user()->admin == 1)   
                    <form method="POST" action="{{ route('users.destroy', [$user->id]) }}">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button title="Delete" class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Êtes-vous sûre de vouloir suprimer ce compte?')"><i class="fa fa-fw fa-trash"></i></button>
                    </form>   
                @endif
            
            <span class="text-muted">{{trans('app.worked_at')}}: {{$user->company}}</span>
            <p class="card-text">{{mb_substr(strip_tags($user->description),0,100)}}...</p>
            <p class="card-text">
                {{(isset($user->experience))?$user->experience:''}} {{trans('app.years_experience')}}
            </p>
            <p>
                
                <?php $skills=explode(",",$user->skills);
                 
                 ?>
                @if(count($skills)>1)
                <h6>{{trans('app.skills')}}</h6>
                @foreach($skills as $skill)
                <a href="#" class="badge badge-dark badge-pill">{{$skill}}
                </a>
                @endforeach

                @else
                <h6>{{trans('app.no_skills-earned_yet')}}</h6>
                @endif

            </p>
            <p>
                <i class="fa fa-map-marker">
                    {{$user->location}}
                </i>
            </p>
           
             
             <div style="display:inline-block;">
                 <a  href="{{route('users.show',$user->username)}}" class="btn btn-info">{{trans('app.view_user')}}</a> 
             </div>
            
            <br><br>
          </div>

        <div class="w-100"></div>
        <div class="card-footer w-100 text-muted">
            {{trans('app.joined').'  '.(new Carbon\Carbon($user->created_at))->diffForHumans()}}
        </div>
    </div>
    <br>
</div>
@endforeach
</div>

<script type="text/javascript">
    function Mysort() {
    // Declare variables
    var input, filter, listDiv, span, h4, i;
    input = document.getElementById('mysearch');
    filter = input.value.toUpperCase();
    listDiv = document.getElementById("list");
    h4 = listDiv.getElementsByTagName('h4');

    // Loop through all list items, and hide those who don't match the search query
    for (i = 0; i < h4.length; i++) {
        span = h4[i].getElementsByTagName("span")[0];
        var parentDiv=h4[i].parentNode.parentNode.parentNode;
        if (span.innerHTML.toUpperCase().indexOf(filter) > -1) {
            parentDiv.style.display = "";
        } else {
            parentDiv.style.display = "none";
        }
    }
}
</script>