routes/web.php
<?php
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('modify-migration', function(){
  $result = DB::table('migrations')->where('id',13)->delete();
  $result = DB::table('migrations')->get();
  print($result);
});
Route::get('services',function(){
  return view('services');
});
Route::get('language/{lang}','HomeController@changeLanguage');
Route::post('add_skills','UserController@addSkills');
Route::get('publishBlog/{slug}','HomeController@publishBlog');
Route::get('publishWork/{slug}','HomeController@publishWork');
Route::get('unpublishWork/{slug}','HomeController@unpublishWork');
Route::get('unpublishBlog/{slug}','HomeController@unpublishBlog');
Route::get('search','BlogController@searchByKeyword');
Route::get('vote','BlogController@voteArticle');
Route::post('update-password','UserController@changePassword');
Route::get('update-password',function(){
  return view('auth.passwords.update');
})->middleware('auth');

/*Route::get('portofolio',function(){
  return view('portofolio');
});
Route::get('blog',function(){
   return view('blog');
});*/
Route::get('new-web-case', function(){
  return view('newwebdesign');
});
Route::get('new-ui-case', function(){
  return view('newuidesign');
});

Route::post('newuicase','newcaseController@storeui');
Route::get('new-seo-case', function(){
  return view('newposterdesign');
});
Route::get('new-seo-case/{id}','newcaseController@storeSeoClient');
Route::get('new-web-case/{id}','newcaseController@storeWebClient');
Route::get('new-ui-case/{id}','newcaseController@storeMobileClient');
Route::post('newpostercase','newcaseController@storeposter');
Route::post('newwebcase','newcaseController@storeweb');
Route::get('/', function () {
    return redirect('home');
});
Route::get('newcase',function(){
	return view('newcase');
});
Route::get('remove-skill/{skill}','UserController@removeSkill');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('newcase','newcaseController@store');
Route::resource('blog','BlogController');
Route::post('message','HomeController@sendMessage');
Route::resource('portofolio','PortofolioController');
Route::get('add-user',function(){
  return redirect()->route('users.create');
})->middleware('auth');
Route::resource('users','UserController');
Route::get('/oauth/github', 'AuthController@redirectToProvider');
Route::get('/oauth/github/callback', 'AuthController@handleProviderCallback');
Route::post('change_pic','AuthController@changePic');
Route::get('/savecookie','newcaseController@savecookie');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/blog_css.blade.php
<style>

/* Header/Blog Title */
.header {
    padding: 30px;
    font-size: 40px;
    text-align: center;
    background: white;
}

/* Create two unequal columns that floats next to each other */
/* Left column */
.leftcolumn {   
    float: left;
    width: 75%;
}

/* Right column */
.rightcolumn {
    float: left;
    width: 25%;
    padding-left: 20px;
}

/* Fake image */
.fakeimg {
    background-color: #f7fdff;
    width: 100%;
    padding: 20px;
}

/* Add a card effect for articles */
.card {
     background-color: white;
     padding: 20px;
     margin-top: 20px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}
.sidebarimg{
    height:70px;
    width:100%;
}
.blogmainimg{
    width:100%;
    height:100%;
}


/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
    .leftcolumn, .rightcolumn {   
        width: 100%;
        padding: 0;
    }
}
</style>

resources/views/layouts/footer.blade.php
<!-- Contact -->

    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">{{trans('app.leave_me_message')}}</h2>
            <h3 class="section-subheading text-muted">{{trans('app.i_always_reply')}}</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            @if(session()->has('status'))
              <div class="alert alert-success">
                {{session('status')}}
              </div>
            @endif
            <form id="contactForm" name="sentMessage" novalidate="novalidate" action="{{url('message')}}" method="post">
              {{csrf_field( )}}
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input name="name" class="form-control form-control-lg{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" type="text" placeholder="{{trans('app.your_name')}} *" value="{{old('name')}}" required>
                    @if ($errors->has('name'))
                        <span class="help-block text-danger" style="color:red" role="alert">
                            <strong>{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                  </div>
                  <div class="form-group">
                    <input name="email" class="form-control form-control-lg{{ $errors->has('email') ? ' is-invalid' : '' }}" id="email" type="email" placeholder="{{trans('app.your_email')}} *" value="{{old('email')}}" required>
                    @if ($errors->has('email'))
                        <span class="help-block text-danger" style="color:red" role="alert">
                            <strong>{{ $errors->first('email') }}</strong>
                        </span>
                    @endif
                  </div>
                  <div class="form-group">
                    <input name="phone" class="form-control form-control-lg{{ $errors->has('phone') ? ' is-invalid' : '' }}" value="{{old('phone')}}" id="phone" type="tel" placeholder="{{trans('app.your_phone')}} eg: +226xxxxxxxx" >
                     @if ($errors->has('email'))
                        <span class="help-block text-danger" style="color:red" role="alert">
                            <strong>{{ $errors->first('phone') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <textarea name="message" class="form-control  form-control-lg{{ $errors->has('message') ? ' is-invalid' : '' }}"  id="message" placeholder="{{trans('app.your_message')}} *" required>{{old('message')}}</textarea>
                    @if ($errors->has('message'))
                        <span class="help-block text-danger" style="color:red" role="alert">
                            <strong>{{ $errors->first('message') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-12 text-center">
                  <div id="success"></div>
                  <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit" style="background-color:#4B65C8;">{{trans('app.send_message')}}</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <span class="copyright">Copyright &copy; {{env('APP_NAME')}} {{date('Y')}}</span>
          </div>
          <div class="col-md-4">
            <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-twitter"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-facebook"></i>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <i class="fa fa-linkedin"></i>
                </a>
              </li>
            </ul>
          </div>
          <div class="col-md-4">
            <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>

resources/views/layouts/head.blade.php
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    @if(isset($currentBlog))
    <meta name="og:description" content="{{$currentBlog->subtitle}}">
    @elseif(isset($work))
    <meta name="og:description" content="{{$work->subtitle}}">
    @elseif(isset($user))
    <meta name="description" content="{{trans('app.skills').': '.$user->skills.' ,'.trans('app.location').':/ '.$user->location}}">
    @else
    <meta name="description" content="{{trans('app.description')}}">
    @endif
    
    @if(isset($currentBlog))
    <meta name="og:image" content="{{asset('img/blog/'.$currentBlog->image)}}">
    @elseif(isset($work))
    <meta name="og:image" content="{{asset('img/portfolio/'.$work->image)}}">
    @elseif(isset($user))
    <meta name="og:image" content="{{asset('img/users/'.$user->image)}}">
    @else
    <meta name="og:image" content="{{asset('img/banner_50.png')}}">
    @endif
    
    <meta name="author" content="">
    <meta name="keywords" content="{{trans('app.keywords')}}">
    @if(isset($currentBlog))
    <title>{{$currentBlog->title}}</title>
    @elseif(isset($work))
    <title>{{$work->title}}</title>
    @elseif(isset($user))
    <title>{{$user->username}}</title>
    @else
    <title>@yield('title')</title>
    @endif
    <!-- Bootstrap core CSS -->
    <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{{asset('css/carousel.css')}}">
    <!-- Custom fonts for this template -->
    <link href="{{asset('vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
  
    <!-- Custom styles for this template -->
    <link href="{{asset('css/agency.min.css')}}" rel="stylesheet">
    <!-- dependency: React.js -->
    <script src="{{asset('js/react-with-addons.js')}}"></script>
    <script src="{{asset('js/react-dom.js')}}"></script>
    <script src="{{asset('js/browser.min.js')}}"></script>

    <!-- Literally Canvas -->
    
  <style type="text/css">
    .carouselImage{
      width: 90px; 
      height: 90px; 
    margin: 0 auto;
    border-radius: 50%;
    border: 1px solid #5db4c0;
    margin-top:2%;
    margin-bottom:0%;
    }
    .mystudies {
      margin-bottom:5%;
      
    }
    .myskills{
      margin-bottom:5%;
      margin-top: 5%;
    }
    .profileimage{
    width:150px;
    height: 150px;
}
.container{
    margin-top:0%;
}

.row-with-filter{
    position: relative;
    z-index: 100000; /* Set a higher z-index to ensure it appears above other elements */
  }
  .fixed-filter-row {
    position: sticky;
    top: 15%;
    width: 100%;
    background-color: #fff; /* Add your desired background color */
    padding: 10px; /* Optional: Add some padding for styling */
    z-index: 1000;
  }

  /* Add a margin to the content below the fixed row to prevent it from being hidden */
  .content-margin {
    margin-top: 40px;
    
  }

  </style>
  

resources/views/layouts/index.blade.php
<!DOCTYPE html>
<html >
<head>
  @include('layouts.head')

</head>
  

  <body id="page-top">

    @include('layouts.nav')

    <!-- Header -->
    <header class="masthead">
      <div class="container">
      
      
      <div class="intro-text" style="color:black;">
        <div class="box col-md-12" style="background-color: rgba(255, 255, 255, 0.5); width:100%;">
          <div class="intro-lead-in">{{trans('app.welcome_message')}}</div>
          <div class="intro-heading text-uppercase" style="font-size:30px;">{{trans('app.welcome_message_continue')}}</div>
        </div>
         @include('shared.search-form')
        </div>
      
      </div>
      
    </header>

   
<!-- my latest posts-->

    <!-- About -->
   
<div id="blog">
<section class="bg-light" id="portfolio">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">{{trans('app.latest_bog_post')}}</h2>
            
          </div>
        </div>
        
         @yield('blog')
        
      </div>
      
    </section>
</div>
    
    @include('layouts.footer')

    <!-- Portfolio Modals -->

    @yield('modals')

    @include('layouts.index_js')

  </body>

</html>

resources/views/layouts/index_js.blade.php
<!-- Bootstrap core JavaScript -->
    <script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>
    <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>


    <!-- Plugin JavaScript -->
    <script src="{{asset('vendor/jquery-easing/jquery.easing.min.js')}}"></script>

    <!-- Contact form JavaScript -->
    <script src="{{asset('js/jqBootstrapValidation.js')}}"></script>
    <script src="{{asset('js/contact_me.js')}}"></script>

    <!-- Custom scripts for this template -->
    <script src="{{asset('js/agency.min.js')}}"></script>

resources/views/layouts/login-template.blade.php
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="vendor/jquery/jquery.min.js"></script>
<style>
body {font-family: Arial, Helvetica, sans-serif;
}

/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}
#login_button{
  margin-top: 5%;
  margin-left: 20%;
  margin-right:20%;
  width:100%;
  padding-right:30%;
  padding-left:30%;
  text-align:center;
  border-radius:6px;
  background-color: #4B65C8;
  font-size: 15px;
  font-weight: bolder;
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
</head>
<body>

<!--<h2>{{trans('app.login')}}</h2>-->
<!--<img src="https://i.gifer.com/Jv9a.gif" style=" width:80%;margin-bottom:3%;display: inline-block; ">-->
<button id="login_button" onclick="document.getElementById('id01').style.display='block'" style="width:auto; display:inline-block;">@yield('login_button')</button>

<div id="id01" class="modal">
  
  <form class="modal-content animate" method="post" action="{{route('login')}}">
    @csrf
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="img/500design.png" alt="Avatar" class="avatar" style="width:20%;height: 20%;">
    </div>

    <div class="container">
      <label for="uname"><b>{{trans('app.email')}}</b></label>
      <input class="{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" type="text" placeholder="{{trans('app.email')}}"  required>

      @if ($errors->has('email'))
        <span class="invalid-feedback">
        <strong>{{ $errors->first('email') }}</strong>
        </span>
      @endif

      <label for="psw"><b>{{trans('app.password')}}</b></label>
      <input class="{{ $errors->has('password') ? ' is-invalid' : '' }}" type="password" placeholder="{{trans('app.enter_password')}}" name="password" required>
      @if ($errors->has('password'))
       <span class="invalid-feedback">
         <strong>{{ $errors->first('password') }}</strong>
       </span>
      @endif
        
      <button style="background-color:#4B65C8" type="submit">{{trans('app.login')}}</button>
      <label>
        <input type="checkbox" checked="checked" name="remember">{{trans('app.rebember_me')}}
      </label>
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <a href="{{url()->previous()}}"  class="cancelbtn">{{trans('app.cancel')}}</a>
      <span class="psw"><a href="{{ route('password.request') }}">{{trans('app.password')}} {{trans('app.forgot')}}?</a></span>

    </div>
    <div class="container" style="text-align:center;">
       <a href="{{url('home#contact')}}" class="login_button" type="button">
          {{trans('app.join_the_community')}}
    </a> 
    </div>
    
  </form>
  
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
window.onload=function(){
  $("#login_button").click();
}
</script>

</body>
</html>

resources/views/layouts/nav.blade.php
 <!-- Navigation -->
    <nav style="background: white;" class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{{url('home')}}">
          <img src="{{asset('img/500design.png')}}" width="30%">
          <span style="font-family:Tahoma; color:#AED9D6;"></span>
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav text-uppercase ml-auto">
            <li class="nav-item">
              <a style="color:black;" class="nav-link js-scroll-trigger" href="{{url('home')}}"></a>
            </li>
            <li class="nav-item dropdown" style="display:none;">
 <a style="color:black;" id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
  {{ trans('app.my_services') }} 
  <span class="caret">
  </span>
  </a>

<div style="position:auto;"  class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
  <a style="color:black;" class="dropdown-item" href="{{url('new-web-case')}}">{{trans('app.web_dev')}}
  </a>
  <a style="color:black;" class="dropdown-item" href="{{url('new-ui-case')}}">{{trans('app.mobile_dev')}}
  </a>
  <a style="color:black;" class="dropdown-item" href="{{url('new-seo-case')}}">{{trans('app.seo')}}
  </a>
  
  <a style="color:black;" class="dropdown-item" href="{{url('services')}}">{{trans('app.see_all')}}
  </a>
  
  
  </div>
  </li>
            <li class="nav-item" style="display: none;">
              <a style="color:black;" class="nav-link js-scroll-trigger" href="{{url('portofolio')}}">{{trans('app.my_work')}}</a>
            </li>
           
            <li class="nav-item">
              <a style="color:black;" class="nav-link js-scroll-trigger" href="{{route('blog.index')}}">{{trans('app.read')}}</a>
            </li>
             <li class="nav-item">
              <a style="color:black;" class="nav-link js-scroll-trigger" href="{{route('blog.create')}}">{{trans('app.write')}}</a>
            </li>
            <!--<li class="nav-item">
              <a style="color:black;" class="nav-link js-scroll-trigger" href="{{url('services')}}">{{trans('app.pricing')}}</a>
            </li>-->
            @if(Auth::check())
            
             <li class="nav-item dropdown">
             <a style="color:black;" id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
              <i class="fa fa-user"></i>
              <span class="caret">
              </span>
              </a>

            <div style="position:auto;"  class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <a style="color:black;" class="dropdown-item" style="font-size:10pt;">
                Salut {{Auth::user()->name}}
              </a>
              <a style="color:black;" class="dropdown-item" href="{{route('users.show',Auth::user()->username)}}">{{trans('app.profile')}}
              </a>
              @if(Auth::user()->admin==1)
              <a style="color:black;" class="dropdown-item" href="{{route('users.create')}}">{{trans('app.new_user')}}
              </a>
              <a style="color:black;" class="dropdown-item" href="{{route('users.index')}}">{{trans('app.view_users')}}
              </a>
              @endif
              <a style="color:black;" class="dropdown-item" href="{{url('update-password')}}">{{trans('app.change_password')}}</a>
              <a style="color:black;" class="dropdown-item" href="{{ route('logout') }}"
                                                   onclick="event.preventDefault();
                                                                 document.getElementById('logout-form').submit();">
                                                    {{ __('app.Logout') }}
                                                </a>

              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                 @csrf
              </form>
            </div>
      </li>
  @else
      <li class="nav-item">
      <a style="color:black;" class="nav-link js-scroll-trigger" href="{{url('login')}}">{{trans('app.login')}}</a>
    </li>    
  @endif
</ul>
<div class="dropdown" style="display:none;">
  <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">{{App::getLocale()}}
  <span class="caret"></span></button>
  <ul class="dropdown-menu" style="text-align:left;width:50%; float:left;margin-left:10%;">
    @if(App::getLocale()=='fr')
    <li><a  style="color:black;" href="{{url('language/en')}}">En</a></li>
    @else
    <li><a style="color:black;" href="{{url('language/fr')}}">Fr</a></li>
    @endif
    
    
  </ul>
</div>

        </div>
      </div>
    </nav>

resources/views/layouts/partners.blade.php
<section class="py-5">
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-sm-6">
            <a href="#">
              <img class="img-fluid d-block mx-auto" src="img/logos/envato.jpg" alt="">
            </a>
          </div>
          <div class="col-md-3 col-sm-6">
            <a href="#">
              <img class="img-fluid d-block mx-auto" src="img/logos/designmodo.jpg" alt="">
            </a>
          </div>
          <div class="col-md-3 col-sm-6">
            <a href="#">
              <img class="img-fluid d-block mx-auto" src="img/logos/themeforest.jpg" alt="">
            </a>
          </div>
          <div class="col-md-3 col-sm-6">
            <a href="#">
              <img class="img-fluid d-block mx-auto" src="img/logos/creative-market.jpg" alt="">
            </a>
          </div>
        </div>
      </div>
    </section>